version: '3'

services:
 app:
  build: .
  image: maicommr/laravel-app
  container_name: app
  volumes:
   - .:/var/www
  networks:
   - app-network                                                                                                                        
  depends_on:
   - db
   - redis
  entrypoint: "dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 30s ./.docker/entrypoint.sh"
  environment:
   - DB_HOST=db
   - DB_PORT=3306
   - DB_DATABASE=db_events
   - DB_USERNAME=root
   - DB_PASSWORD=root

 nginx:
  build: .docker/nginx
  container_name: nginx
  entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off";
  environment:
   - APP_NAME=app
   - APP_PORT=9000
  restart: always
  tty: true
  ports:
   - "8000:80"
  volumes:
   - .:/var/www
  networks:
   - app-network
  depends_on:
   - app
  # entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d



 redis:
  image: redis:alpine
  expose:
   - 6379
  networks:
    - app-network

 db:
  image: mysql:5.7
  command: --innodb-use-native-aio=0
  container_name: db
  restart: always
  tty: true
  user: "1000"
  ports:
   - "3306:3306"
  environment:
   - MYSQL_DATABASE=db_events
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=root
  networks:
   - app-network
  volumes:
   - ./.docker/dbdata:/var/lib/mysql

networks:
 app-network:
  driver: bridge